spring.application.name=api-gateway


# Server
server.port=8082

# Management
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Gateway security
app.security.jwt.secret=api-gateway-dev-secret-api-gateway-dev-secret
app.security.jwt.public-paths[0]=/auth/login
app.security.jwt.public-paths[1]=/auth/register
app.security.jwt.public-paths[2]=/auth/refresh
app.security.jwt.public-paths[3]=/actuator/health
app.security.jwt.public-paths[4]=/actuator/info

# ? AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://192.168.8.10:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /api/v1/auth/$\{segment}

# ? VOUCHER SERVICE
spring.cloud.gateway.routes[1].id=voucher-service
spring.cloud.gateway.routes[1].uri=http://192.168.8.74:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/voucher/**

# ? WALLET SERVICE
spring.cloud.gateway.routes[2].id=wallet-service
spring.cloud.gateway.routes[2].uri=http://192.168.8.10:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/wallet/**

# ? ORDER SERVICE
spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=http://192.168.8.94:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/order/**

# ? KYC SERVICE
spring.cloud.gateway.routes[4].id=kyc-service
spring.cloud.gateway.routes[4].uri=http://192.168.8.133:8080
spring.cloud.gateway.routes[4].predicates[0]=Path=/kyc/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
